language: php

sudo: false

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.composer/cache

php:
  - "7.1"
  - "7.2"
  - "7.3"

install:
  - travis_retry composer update --no-suggest --no-interaction
  - composer info

script:
  - vendor/bin/phpunit
